create table FSREMWENV_DART(
    id integer not null primary key,
    POD_NAME VARCHAR2(30),
    comp_type varchar2(50),
    json_data clob check (json_data is json),
    collected TIMESTAMP DEFAULT sysdate
);

CREATE TABLE dbart_stage_temp_test(
   id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY(START WITH 1),
   J_data CLOB CHECK (J_data IS JSON),
   collected_time TIMESTAMP not null,
   pod_name VARCHAR2(100) not null,
   CREATED TIMESTAMP DEFAULT sysdate
) LOB (c) STORE AS (CACHE) ;

create table FSREMWENV_EXA_OCTO(
    id integer not null primary key,
    exa_name VARCHAR2(200),
    json_data clob check (json_data is json),
    collected TIMESTAMP DEFAULT sysdate
);

create table FSREMWENV_SQLDF(
    id integer not null primary key,
    total_seconds NUMBER(30),
    aas NUMBER(30),
    distinct_sql_executions NUMBER(30),
    dart_time varchar2(50),
    sql_id varchar2(50),
    module varchar2(50),
    per_exec_time varchar2(50),
    sql_details varchar2(50),
    collected TIMESTAMP DEFAULT sysdate
    );

ALTER TABLE FSREMWENV_SQLDF 
MODIFY sql_details varchar2(100) ;

ALTER TABLE FSREMWENV_SQLDF 
ADD POD varchar2(50) ;