CREATE SEQUENCE row_id
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE exa_octo_row_id
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE FSREMWENV_SQLDF_id
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;